### ISSUE TITLE
srhs returnerer ikke i samme rækkefølge som elementerne kommer 

### ISSUE THREAD

**Issue by FabianScott** [PBonvang/Mat1Tools-maple#6]
![image](https://user-images.githubusercontent.com/76645786/167602511-10e7560b-8412-447e-a4a1-cc73cc4553c7.png)

**Comment by PBonvang** [comment]
Problemet er at set ikke har order/rækkefølge, så det kan ikke programmatisk lade sig gøre. En workaround er at smide en anden output type på som har order fx. list eller Vector:
![image](https://user-images.githubusercontent.com/36742219/167633397-3276d489-0eb3-4cf2-92b7-14831558c091.png)
